-- Built-in beer catalog (mirrors BEER_CATALOG in src/data/beers.ts).
insert into public.beers (id, name, brewery, style, abv) values
  ('hazy-little-thing', 'Hazy Little Thing', 'Sierra Nevada', 'Hazy IPA', 6.7),
  ('sierra-nevada-pale-ale', 'Pale Ale', 'Sierra Nevada', 'Pale Ale', 5.6),
  ('guinness-draught', 'Guinness Draught', 'Guinness', 'Stout', 4.2),
  ('pliny-the-elder', 'Pliny the Elder', 'Russian River', 'IPA', 8.0),
  ('fat-tire', 'Fat Tire', 'New Belgium', 'Amber', 5.2),
  ('voodoo-ranger', 'Voodoo Ranger IPA', 'New Belgium', 'IPA', 7.0),
  ('juicy-haze', 'Juicy Haze', 'New Belgium', 'Hazy IPA', 7.5),
  ('pilsner-urquell', 'Pilsner Urquell', 'Plzeňský Prazdroj', 'Pilsner', 4.4),
  ('founders-breakfast-stout', 'Breakfast Stout', 'Founders', 'Stout', 8.3),
  ('founders-all-day-ipa', 'All Day IPA', 'Founders', 'Session IPA', 4.7),
  ('murphys-stout', 'Murphy’s Irish Stout', 'Heineken Ireland', 'Stout', 4.0),
  ('london-porter', 'London Porter', 'Fuller’s', 'Porter', 5.4),
  ('london-pride', 'London Pride', 'Fuller’s', 'Bitter', 4.7),
  ('old-rasputin', 'Old Rasputin', 'North Coast', 'Imperial Stout', 9.0),
  ('berliner-weisse', 'Berliner Weisse', 'Schneeeule', 'Sour', 3.0),
  ('hitachino-white', 'Hitachino Nest White Ale', 'Kiuchi', 'Witbier', 5.5),
  ('shiner-bock', 'Shiner Bock', 'Spoetzl', 'Bock', 4.4),
  ('zombie-dust', 'Zombie Dust', '3 Floyds', 'Pale Ale', 6.2),
  ('two-hearted', 'Two Hearted', 'Bell’s', 'IPA', 7.0),
  ('lagunitas-ipa', 'Lagunitas IPA', 'Lagunitas', 'IPA', 6.2),
  ('blue-moon', 'Blue Moon Belgian White', 'Blue Moon', 'Witbier', 5.4),
  ('weihenstephaner-hefe', 'Hefeweissbier', 'Weihenstephaner', 'Wheat', 5.4),
  ('duvel', 'Duvel', 'Duvel Moortgat', 'Belgian Strong', 8.5),
  ('heineken', 'Heineken', 'Heineken', 'Lager', 5.0),
  ('stella-artois', 'Stella Artois', 'AB InBev', 'Lager', 5.0),
  ('modelo-especial', 'Modelo Especial', 'Grupo Modelo', 'Lager', 4.4),
  ('sapporo', 'Sapporo Premium', 'Sapporo', 'Lager', 4.9)
on conflict (id) do update set name = excluded.name, brewery = excluded.brewery, style = excluded.style, abv = excluded.abv;
